#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log.setFields
rm -rf log.decomposePar
rm -rf log.reconstructPar
rm -rf postProcessing
rm -rf processor*

runApplication setFields

runApplication decomposePar
runParallel foamRun
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
