#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh

snappyHexMesh -overwrite

list=( front back )
for item in "${list[@]}"; do
    foamDictionary constant/polyMesh/boundary -entry entry0/${item}/type -set empty
    foamDictionary constant/polyMesh/boundary -entry entry0/${item}/inGroups -set "List<word> 1(empty)"
done

decomposePar
mpirun -np 4 foamRun -parallel
reconstructPar -latestTime
